name: Android Upload Release CI

on:
  release:
    types: [created]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build apk file with Gradle
      run: ./gradlew assembleDebug
    - name: Show file tree
      run: |
        sudo apt-get -y install tree
        tree
    - name: Upload apk file
      run: gh release upload ${{ github.ref:10}} app/build/outputs/apk/debug/app-debug.apk
      env:
        GH_TOKEN: ${{ github.token }}
