name: Android Upload Release CI

on:
  release:
    types: [prereleased]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build apk file with Gradle
      run: ./gradlew assembleDebug
      env:
        jkspwd: ${{ secrets.JKSPWD }}
    - name: Get version code
      id: version
      run: echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
    - name: Upload apk file
      run: gh release upload ${{steps.version.outputs.VERSION}} app/build/outputs/apk/debug/app-debug.apk
      env:
        GH_TOKEN: ${{ github.token }}
